test01:
	python3 main.py tests/inputs/input1.txt tests/operations/op1.txt tmp1.txt otp1.txt

test02:
	python3 main.py tests/inputs/input2.txt tests/operations/op2.txt tmp2.txt otp2.txt

test03:
	python3 main.py tests/inputs/input3.txt tests/operations/op3.txt tmp3.txt otp3.txt

clean:
	rm -rf __pycache__
	rm *.txt